Lesson3
Gwellir/gb_JS_adv pull request #3
Opened 2020-06-29 12:13 UTC by Gwellir

2020-07-05 21:27 UTC, Om1X requested changes
Довести до рабочего состояния

2020-07-05 21:27 UTC, Om1X commented on lesson3/project/js/main.js
> +        let total = this.goods.reduce(function(sum, item) {
можно опустить let total и сделать сразу return this.goods.reduce(...);

2020-07-05 21:27 UTC, Om1X commented on lesson3/project/js/main.js
> +        return this.basketList.filter( (item) => item.id_product === id)[0];
здесь уместней метод Array.find

2020-07-05 21:27 UTC, Om1X commented on lesson3/project/js/main.js
> +        let apiAction = (action === 'delete' ? 'deleteFromBasket' : 'addToBasket');
Задумка интересная, но не стоит перебарщивать с ним. Если и применять, то тут стоило apiAction сделать в виде объекта с соответствующими ключами (delete, add, ...)

2020-07-06 06:40 UTC, Gwellir commented
дописал до рабочего вида, старался не полностью копировать логику, вышло кривовато, перед пятым заданием прикину, что ещё можно поправить

2020-07-07 13:42 UTC, merged